import Header from '@/components/Header'
import { ReactNode } from 'react'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function BooksLayout({ children }: { children: ReactNode }) {
  return (
    <div className="h-screen bg-[#5FE9C6]">
      <Header isAuthenticated />
      {children}
    </div>
  )
}
